// This file is used to test the API Endpoints

### Test Route to ensure API can actually connect
GET http://localhost:8082/api/compactor/test

### GET ALL Testing [Compactor API]
GET http://localhost:8082/api/compactor

### GET ONE Testing [Compactor API]
GET http://localhost:8082/api/compactor/62bbd9268364a01f858ec0a6

### POST Testing [Compactor API]
POST http://localhost:8082/api/compactor
Content-Type: application/json

{
    "compactorID": "A",
    "items": {
        "item1": 1,
        "item2": 2,
        "item3": 3,
        "item4": 4,
        "item5": 5,
        "item6": 69
    }
}

### UPDATE Testing [Compactor API]
PATCH http://localhost:8082/api/compactor/62bbd9268364a01f858ec0a6
Content-Type: application/json

{
    "compactorID": "A",
    "items": {
        "item1": 6,
        "item2": 6,
        "item3": 6,
        "item4": 6,
        "item5": 6,
        "item6": 6
    }
}

### DELETE Testing [Compactor API]
DELETE http://localhost:8082/api/compactor/62bc0d300d28f04bf82f2135

