// This file is used to test the API Endpoints
// Download VSCode Extension "REST Client by Huachao Mao"
// Copy .env file into the Root Folder with Mongo_URI from Paul/Shaan

### Test Route to ensure API can actually connect
GET http://localhost:8082/api/compactor/test

### GET ALL Testing [Compactor API]
GET http://localhost:8082/api/compactor

### POST Testing [Compactor API]
POST http://localhost:8082/api/compactor
Content-Type: application/json

{
    "compactorID": "1",
    "items": [
        {
            "itemName": "crutches",
            "itemQuantity": 5
        },
        {
            "itemName": "walking frame",
            "itemQuantity": 4
        },
        {
            "itemName": "walking stick",
            "itemQuantity": 3
        }
    ]
}

### GET ONE by ObjectID Testing [Compactor API]
GET http://localhost:8082/api/compactor/mongoID/62d15784617218727fc38512

### UPDATE Testing by ObjectID [Compactor API]
PATCH http://localhost:8082/api/compactor//mongoid/62d15784617218727fc38512
Content-Type: application/json

{
    "compactorID": "1",
    "items": [
        {
            "itemName": "crutches",
            "itemQuantity": 5
        },
        {
            "itemName": "walking frame",
            "itemQuantity": 4
        },
        {
            "itemName": "walking stick",
            "itemQuantity": 1
        },
        {
            "itemName": "running stick",
            "itemQuantity": 2
        }
    ]
}

### DELETE Testing by ObjectID [Compactor API]
DELETE http://localhost:8082/api/compactor/mongoid/62d15784617218727fc38512

### GET ONE by Compactor Number Testing [Compactor API]
GET http://localhost:8082/api/compactor/1

### UPDATE Testing by Compactor Number [Compactor API]
PATCH http://localhost:8082/api/compactor/1
Content-Type: application/json

{
    "compactorID": "1",
    "items": [
        {
            "itemName": "crutches",
            "itemQuantity": 1
        },
        {
            "itemName": "walking frame",
            "itemQuantity": 1
        },
        {
            "itemName": "walking stick",
            "itemQuantity": 1
        },
        {
            "itemName": "running stick",
            "itemQuantity": 1
        }
    ]
}

### DELETE Testing by Compactor Number [Compactor API]
DELETE http://localhost:8082/api/compactor/1

